### ISSUE TITLE
Can't run birdie example anymore because of Element `getindex`

### ISSUE THREAD

**Issue by emsal0** [HSU-ANT/ACME.jl#68]
```
julia> circ = Circuit()
Circuit(OrderedCollections.OrderedDict{Symbol, ACME.Element}(), Vector{Tuple{Symbol, Symbol}}[], Dict{Symbol, Vector{Tuple{Symbol, Symbol}}}())

julia> connect!(circ, j3[:+], c5[2], d1[:-], :vcc)
ERROR: MethodError: no method matching getindex(::ACME.Element, ::Symbol)
Stacktrace:
 [1] top-level scope
   @ REPL[5]:1
```

I understand that `getindex` was probably removed in commit a300ee5a49310736830ad61c5070a9c9fe125267 or some similar change, but if that's the case then what's the new paradigm for connecting circuit elements if you want to do it outside of the `@Circuit` DSL construction?

**Comment by martinholters** [comment]
https://github.com/HSU-ANT/ACME.jl/blob/f694e321acea4e5fb92d7093c967f395d2f771ed/src/circuit.jl#L163-L177

So the call now has to look like
```julia
connect!(circ, (:j3, :+), (:c5, 2), (:d1, -), :vcc)
```
If I got the archaeology right, the old syntax has been deprecated in v0.5.0 (Nov 14, 2017) and finally removed in v0.8.0 (Mar 13, 2019). Remarkable that this surfaces now...
